### ISSUE TITLE
Baseline Code

### ISSUE THREAD

**Issue by zhazhat** [intelligolabs/HARPER#1]
Hello, can you provide the baseline code for 3D pose estimation and motion prediction in the paper?

**Comment by federicocunico** [comment]
Dear @zhazhat thank you for reaching us out. 
The code for 2D human pose estimation is the HRNet, we used a pytorch implementation: https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/tree/master/demo
For the 3D pose estimation we lifted using the the HRNet + depth data (using the 'visibles_3d' key in the annotations). 
For the motion prediction, we used the official implementation of the methods (i.e. EQMotion).

We will release soon our validation code.

**Comment by zhazhat** [comment]
Ok, thank you for your quick answer! I would like to ask whether your method can achieve online prediction in real scenarios. I look forward to your work.

**Comment by federicocunico** [comment]
At the current state, no. This is a limitation we are currently investigating for future works.
The 3D pose forecasting is technically able to do it (since they are approaches with "sliding window" behaviour). However, the reconstruction of the full pose requires the full sequence to re-create the skeleton (take a look at the paper to have a detailed explanation).

**Comment by zhazhat** [comment]
Ok, thanks for your answer
