### ISSUE TITLE
Inquiry regarding access to RGB videos from External RGB Camera

### ISSUE THREAD

**Issue by Necolizer** [intelligolabs/HARPER#3]
Hi, 

Thank you for your outstanding work! I believe your work can greatly benefit HRC studies.

I have a few questions about the structure and names of the repositories in [your onedrive link](https://univr-my.sharepoint.com/:f:/g/personal/federico_cunico_univr_it/Esk9qR4fKyFBg05UdXK0YSYBY8JvLHpY2Bis2xyX1pcVWg):
- Do the `HARPER - 3D panoptic - high fps` and `HARPER - 3D only` directories contain the same 3D keypoint data?
- In the `HARPER` directory, are the `single zips` and `harper.tar.gz` the same? 
- It seems that `single zips` and `harper.tar.gz` consist of videos from Spot's stereo cameras (5 Greyscale + Depth and 1 RGB-D).  Could you please let me know where I can find the RGB videos captured by the External RGB Camera?

I would greatly appreciate any clarification you can provide. Thank you in advance for your help!

Best regards,

**Comment by federicocunico** [comment]
Hi, to answer your questions:
- they are the same, “high fps” data is the 120hz data, the other is downsampled to 30hz. This is because originally the optitrack is captured at 120hz. Since the robot do record at 60hz on average (not stable), we upsampled (interpolated) robot data. The 30 fps version (3D only) is the one supposed to be used for the specific task of human pose forecasting from 3D skeletons (like in CHICO or Human3.6 forecasting). 
- the single zips should be the same as the content of the tar; however, I suggest you to use the script we provided for download. 
- Due to unforeseen limitations of Spot SDK, we struggled to sync the spot cameras with optitrack data. The whole dataset is supposed to take the robot perspective as main contribution, in fact see the HARPER acronym on the paper. For this reason, while we do have External RGBs, they are not aligned with dataset data and for now we are not planning to do it in the immediate future. Anyway we plan to release them before IROS 2024. Stay tuned on that!

**Comment by federicocunico** [comment]
The External RGB frames are being uploaded in the same link you can find in the repo, under the "HARPER - External RGB" folder. 
I want to remind you that these are NOT synchronized yet and are the raw images. You can try to synchronize using the timestamp info saved in the file's name, which is the starting time of the recording. We are not planning to do so right now.

**Comment by Necolizer** [comment]
Thank you for your prompt response and for the helpful reminder! I'll check it out. Really appreciate the effort you’ve put into this work!
